name: Git hub actions perform
on : push

jobs:
  Cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: precommit
        run: npm ci
      - run: npm run precommit
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start 
          browser: chrome


