name: Git hub actions perform
on : push

jobs:
  Cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: precommit
        run: npm ci
      - run: npm run precommit
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          start: npm start 
          browser: chrome

      - name: Uploading Artifacts
        uses: actions/upload-artifact@v3
        if: always()    
        with:
          name: cypress-execution-report
          path: orange_hrm/reports
          retention-days: 30

      - name: Send some mail
        uses: wadeww/send-email-action@master
          with:
          server_address: smtp.gmail.com
          port: 465
          username: kanishkapicaros@gmail.com
          password: secrets.MAIL_PASSWORD
          subject: Workflow finished
          body: Job completed job.status
          to: kanishkapicaros@gmail.com, pulkit.rana221@gmail.com
    from: Me    

